### ISSUE TITLE
Need a workflow to prepare the bsseq object for input

### ISSUE THREAD

**Issue by CharlieL0808** [aryeelab/scmeth#1]
Hi,
I have output files from Bismark, but I am unsure of how to convert these files into bsseq objects for input into scmeth.I primarily want to use the report function.
Could you give me a workflow to prepare the bsseq object for input.
Thank you so much for your help.

**Comment by divy-kangeyan** [comment]
Hi @CharlieL0808 - There is function called read.bismark in bsseq bio conductor package. Checkout this page: https://rdrr.io/bioc/bsseq/man/read.bismark.html

Please run that function and see if it works for your bismark files.

**Comment by CharlieL0808** [comment]
Hi,I successfully used the read.bismark function to construct a bsseq object and ran the report function.
Thanks you very much!
